#!/bin/sh

COVERAGE_ERROR_FILE=coverage.err
LOCAL_COVERAGE_FILE=coverage.out
GLOBAL_COVERAGE_FILE=coverage-all.out

find . -mindepth 1 -name '*_test.go' -exec sh -c "cd \$(dirname {}); go test -covermode=count -coverprofile=$LOCAL_COVERAGE_FILE" \; >/dev/null 2>$COVERAGE_ERROR_FILE
echo 'mode: count' >$GLOBAL_COVERAGE_FILE

LOCAL_COVERAGE_FILES=$(find . -name $LOCAL_COVERAGE_FILE)
if [ -z "$LOCAL_COVERAGE_FILES" ]; then
	echo 'Coverage is not available' >&2
	cat $COVERAGE_ERROR_FILE >&2
	STATUS=1
else
	grep --no-filename -v 'mode: count' $LOCAL_COVERAGE_FILES >>$GLOBAL_COVERAGE_FILE
	rm -f $LOCAL_COVERAGE_FILES

	if [ "$1" = "-html" ]; then
		go tool cover -html=$GLOBAL_COVERAGE_FILE -o ${GLOBAL_COVERAGE_FILE}.html
	fi
fi

rm -f $COVERAGE_ERROR_FILE
exit $STATUS
